name: unit tests
on: 
  push:

jobs:
  unit_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: npm ci
    - name: Run tests
      run: npm run test:unit